server:
  port: 8081

spring:
  datasource:
    url: ${secrets.BRAIN_DB_URL}
    username: ${secrets.BRAIN_DB_USERNAME}
    password: ${secrets.BRAIN_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect