name: brain-back

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/setup-gradle@v1
      with:
        gradle-version: '8.4.0'

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Build Docker image
      run: |
        docker build . -t ${{ secrets.BRAIN_DOCKER_REGISTRY_URL }}/brain-back:latest

    - name: Log into Docker Hub
      run: docker login -u ${{ secrets.BRAIN_DOCKER_USERNAME }} -p ${{ secrets.BRAIN_DOCKER_PASSWORD }}

    - name: Push Docker image to registry
      run: docker push ${{ secrets.BRAIN_DOCKER_REGISTRY_URL }}/brain-back:latest
